version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      # Please note that that the username for this account is SA. 
      SA_PASSWORD: 'Password!2024'
      ACCEPT_EULA: 'Y'
      JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStore=NONE -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT -Djavax.net.ssl.trustStoreProvider=SUN -Dcom.microsoft.sqlserver.jdbc.DSTLProtocol=true" 
    ports:
      - "1433:1433"
    volumes:
      - ../../schema/simple/university-sqlserver.sql:/university-sqlserver.sql
      - ../../schema/simple/populate-university-db.sql:/insert-scripts.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 30 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $${SA_PASSWORD} -i /university-sqlserver.sql &&
      sleep 10 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $${SA_PASSWORD} -d University -i /insert-scripts.sql &&
      while true; do sleep 3600; done
      "
    
profiles:
  simple:
    services:
      mssql:
        volumes:
          - ../../schema/simple/university-sqlserver.sql:/docker-entrypoint-initdb.d/init.sql
          - ../../schema/simple/populate-university-db.sql:/docker-entrypoint-initdb.d/insert-scripts.sql     
  full:
    services:
      mssql:
        volumes:
          - ../../schema/full/university-sqlserver.sql:/docker-entrypoint-initdb.d/init.sql
          - ../../schema/full/populate-university-db.sql:/docker-entrypoint-initdb.d/insert-scripts.sql   