version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: University
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ../../schema/university-postgresql.sql:/docker-entrypoint-initdb.d/init.sql
